config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questionnaires do
    resources :responses
  end
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  root to: 'users#index'
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  namespace :api do
    namespace :v1 do
      resource :answers, only: [] do
        member do
          get :single
        end
      end
    end
  end
  
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  has_one_attached :answerimg
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  enum question_type: { single_choice: 0, multiple_choice: 1, long_answer: 2, satisfaction: 3, date: 4, time: 5,
                        drop_down_menu: 6, range: 7, file: 8, image: 9 }

  def self.question_type_select
    question_types.keys.map { |k| [k.titleize, k] }
  end
end

app/models/questionnaire.rb
# frozen_string_literal: true

class Questionnaire < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

  default_scope {where(deleted_at: nil)}

  def destroy
    update(deleted_at: Time.current)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < ApplicationController
  def single
    render layout: false
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Please login first'
  end
end

app/controllers/questionnaires_controller.rb
# frozen_string_literal: true

class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[show edit update destroy]

  # GET /questionnaires or /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1 or /questionnaires/1.json
  def show; end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit; end

  # POST /questionnaires or /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to questionnaire_url(@questionnaire), notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1 or /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html do
          redirect_to questionnaire_path(@questionnaire), notice: 'Questionnaire was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1 or /questionnaires/1.json
  def destroy
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def questionnaire_params
    params.require(:questionnaire).permit(
      :name,
      questions_attributes: [
        :_destroy,
        :id,
        :question_type,
        :name,
        { answers_attributes: %i[
          _destroy
          id
          name
        ] }
      ]
    )
  end
end

app/controllers/responses_controller.rb
# frozen_string_literal: true

class ResponsesController < ApplicationController
  def new
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[index new create]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
# frozen_string_literal: true

module QuestionnairesHelper
end

app/helpers/user_sessions_helper.rb
# frozen_string_literal: true

module UserSessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div id="nav">
  <% if current_user %>
  <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
  <%= link_to "Logout", :logout, method: :delete %>
  <% else %>
  <%= link_to "Register", new_user_path %> |
  <%= link_to "Login", :login %>
  <% end %>
</div>
<div>
    <p id="notice"><%= notice %></p>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
    <%= yield %>
  </body>
</html>

app/views/questionnaires/_answer_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Answer', class: 'form-control' %>
    <small>
      <%= link_to "Remove Answer", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
</div>

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div data-controller="nested-form" data-nested-form-index-value ="QUESTION_RECORD">
    <template data-nested-form-target='template'>
      <%= form.fields_for :questions, Question.new, child_index: 'QUESTION_RECORD' do |question| %>
        QUESTION - QUESTION_RECORD
        <%= render 'question_fields', form: question %>
      <% end %>
    </template>

    
    <%= form.fields_for :questions do |question| %>
      <%= render 'question_fields', form: question %>
    <% end %>
    

    <div data-nested-form-target="add_item">
      <%= link_to "Add Question", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>

  <div data-controller="answer-item" data-answer-item-target="answer">
    <%= link_to '新增回答', "#", data: { action: "click->answer-item#add_answer" } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaires/_question_fields.html.erb
<div class='nested-fields box' data-controller='dynamic-select'>
  <div class='form-group'>
    <%= form.select :question_type,
        options_for_select(Question.question_type_select, selected: form.object.question_type),
        {},
        'data-dynamic-select-target': 'select',
        'data-action': 'dynamic-select#selected' %>
  </div>

  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Question', class: 'form-control' %>
    <small>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>

  <div data-controller="nested-form" 
       data-nested-form-index-value ="ANSWER_RECORD" data-dynamic-select-target='choice'>
    <template data-nested-form-target='template'>
      <%= form.fields_for :answers, Answer.new, child_index: 'ANSWER_RECORD' do |answer| %>
        ANSWER - ANSWER_RECORD
        <%= render 'answer_fields', form: answer %>
      <% end %>
    </template>

    <%= form.fields_for :answers do |answer| %>
      <%= render 'answer_fields', form: answer %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add Answer", "#", data: { action: "nested-form#add_association" } %>
    </div>
  </div>
  
  <div data-controller="nested-form" data-dynamic-select-target='long'>
  </div>
</div>

app/views/questionnaires/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<h1 class="text-black text-5xl"><%= link_to 'Questionnaires', questionnaires_path %></h1>

<table>
  <thead>
    <tr>
      <th class="text-xl">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr class="border-2">
        <td class="border-2"><%= questionnaire.name %></td>
        <td class="border-2"><%= link_to 'Show', questionnaire %></td>
        <td class="border-2"><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td class="border-2"><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<h1><%= @questionnaire.name %></h1>

<% @questionnaire.questions.each do |question| %>
  <h2><%= question.name %></h2>

  <% case question.question_type %>
  <% when 'single_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= radio_button_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'multiple_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= check_box_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'long_answer' %>
    <%= text_area_tag question.id %>
  <% when 'satisfaction' %>
    <table>
      <tr>
      <% question.answers.each do |answer| %>
        <td>
          <%# radio_button_tag question.id, answer.id %>
          <%= answer.name %>
        </td>
      <% end %>
      </tr>
      <tr>
      <% question.answers.each do |answer| %>
        <td>
          <%= radio_button_tag question.id, answer.id %>
          <%# answer.name %>
        </td>
      <% end %>
      </tr>
    </table>  
  <% when 'date' %>
    <%= date_field_tag question.id %>
  <% when 'time' %>
    <%= time_field_tag question.id %>
  <% when 'drop_down_menu' %>
    <% question.answers.each do |answer| %>
    <%= select_tag question.id, options_for_select(
      [[answer.name, answer.id], [answer.name, answer.id]]) %>
    
      <%# select_tag question.id %>
      <%# question.answers.each do |answer| %>
          
          <%# answer.name %>
        
      <% end %>
  <% when 'range' %>
    <%= range_field_tag question.id %>  
  <% when 'file' %>
    <%= file_field_tag question.id, accept: "application/pdf, application/zip", multiple: true %>  
  <% when 'image' %>
    <%= file_field_tag question.id %>  
      <% question.answers.each do |answer| %>
        <%= image_tag answer.answerimg.variant(resize_to_limit: [200, 300]) %>  
      <% end %>
  <% end %>
<% end %>

<div>
<%= link_to 'New Response', new_questionnaire_response_path(@questionnaire) %>
<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %>
<%= link_to 'Back', questionnaires_path %>
</div>

app/views/responses/new.html.erb
<h1>回答</h1>

<h1><%= @questionnaire.name %></h1>

<% @questionnaire.questions.each do |question| %>
  <h2><%= question.name %></h2>

  <% case question.question_type %>
  <% when 'single_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= radio_button_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'multiple_choice' %>
    <% question.answers.each do |answer| %>
      <p>
        <%= check_box_tag question.id, answer.id %>
        <%= answer.name %>
      </p>
    <% end %>
  <% when 'long_answer' %>
    <%= text_area_tag question.id %>
  <% when 'satisfaction' %>
    <table>
      <tr>
      <% question.answers.each do |answer| %>
        <td>
          <%# radio_button_tag question.id, answer.id %>
          <%= answer.name %>
        </td>
      <% end %>
      </tr>
      <tr>
      <% question.answers.each do |answer| %>
        <td>
          <%= radio_button_tag question.id, answer.id %>
          <%# answer.name %>
        </td>
      <% end %>
      </tr>
    </table>  
  <% when 'date' %>
    <%= date_field_tag question.id %>
  <% when 'time' %>
    <%= time_field_tag question.id %>
  <% when 'drop_down_menu' %>
    <%= select_tag question.id %>
      <%= question.answers.each do |answer| %>
          <%= answer.name %>
      <% end %>
  <% when 'range' %>
    <%= range_field_tag question.id %>  
  <% when 'file' %>
    <%= file_field_tag question.id %>  
  <%# when 'image' %>
    <%# image_tag question.id %>  
  <% end %>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
  <%= form.label :password %><br />
  <%= form.password_field :password %>
</div>
<div class="field">
  <%= form.label :password_confirmation %><br />
  <%= form.password_field :password_confirmation %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>